[package]
name = "netmuxd"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

default-run = "netmuxd"

[[bin]]
name = "test"
path = "src/test.rs"

[[bin]]
name = "passthrough"
path = "src/passthrough.rs"

[dependencies]
tokio = { version = "1.17.0", features = [ "full" ] }
futures-util = { version = "0.3.21" }

zeroconf = { version = "0.14.2", optional = true }
mdns = { version = "3.0.0", optional = true }

rusty_libimobiledevice = { version = "0.1.2", features = [ "static", "vendored" ] }
plist_plus = { version = "0.2.1", features = [ "static", "vendored" ] }

log = { version = "0.4.16" }
env_logger = { version = "0.7.1" }
colored = { version = "2.0.0" }

rusb = { version = "0.9.3", optional = true }
libusb1-sys = { version = "0.6.5", optional = true }

[features]
usb = [ "libusb1-sys", "rusb" ]
default = ["rusb", "zeroconf" ]
